
virtuoso:
    image: namlook/docker-virtuoso:7.2.1
    # image: tenforce/virtuoso:virtuoso-v7.2.0
    ports:
        - "8890:8890"
        - "1111:1111"
    environment:
        DBA_PASSWORD: dba
        SPARQL_UPDATE: true
    restart: always
    privileged: true
    volumes:
        - ~/virtuosodb:/var/lib/virtuoso/db

blazegraph:
    image: lyrasis/blazegraph:1.5.3
    ports:
        - "9999:8080"
    restart: always
    privileged: true
    volumes:
        - ~/blazegraph:/data
