// Generated by CoffeeScript 1.7.1
(function() {
  var deepClone, _;

  _ = require('underscore');

  exports.isPojo = function(obj) {
    return _.isObject(obj) && !_.isArray(obj) && !_.isFunction(obj);
  };

  exports.deepClone = deepClone = function(obj, inherit) {
    var clonedObj, key, value;
    if ((!_.isObject(obj)) || (_.isObject(obj) && (_.isArray(value) || _.isFunction(value)))) {
      return obj;
    }
    clonedObj = {};
    for (key in inherit) {
      value = inherit[key];
      clonedObj[key] = deepClone(value);
    }
    for (key in obj) {
      value = obj[key];
      if (_.isObject(value) && !_.isArray(value) && !_.isFunction(value)) {
        clonedObj[key] = deepClone(value, clonedObj[key]);
      } else {
        clonedObj[key] = value;
      }
    }
    return clonedObj;
  };

}).call(this);
